META_ARC: "siamrpn_r50_l234_dwxcorr"

BACKBONE:
    TYPE: "resnet50"
    KWARGS:
        used_layers: [2, 3, 4]
    PRETRAINED: 'pretrained_models/resnet50.model'
    TRAIN_LAYERS: ['layer2','layer3','layer4']
    TRAIN_EPOCH: 10
    LAYERS_LR: 0.1

ADJUST:
    ADJUST: true
    TYPE: "AdjustAllLayer"
    KWARGS:
        in_channels: [512, 1024, 2048]
        out_channels: [256, 256, 256]

CAR:
    KWARGS:
        in_channels: 256

TRACK:
    TYPE: 'SiamCARTracker'
    EXEMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    CONTEXT_AMOUNT: 0.5
    UPSIZE: 193
    SCORE_SIZE: 25
    hanming: True
    ave_reg: True

TEST:
    NUM_CLASSES: 2
    NUM_CONVS: 4
    PRIOR_PROB: 0.01

HP_SEARCH:
    OTB: [0.15, 0.1, 0.4]
    UAV123: [0.39, 0.04, 0.37]
    VOT2019: [0.41, 0.04, 0.3]
    LaSOT: [0.33, 0.04, 0.40]
    GOT: [0.6, 0.04, 0.1]